image:
  repository: harbor.chenjie.info/chenjie/devops-demo
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  ingressClassName: traefik
  path: /
  hosts:
    - devops-demo.chenjie.info

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
